spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker
spring.datasource.username=root
spring.datasource.password=nitin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




# AI api


gemini.api.key=api key
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash-001:generateContent
